#ifndef MATRIX_CLIENT_MATRIX_EVENT_TYPE_H
#define MATRIX_CLIENT_MATRIX_EVENT_TYPE_H

typedef enum matrix_event_type_t {
    EVENT_UNKNOWN,

    EVENT_ROOM_CREATE,
    EVENT_ROOM_NAME,
    EVENT_ROOM_AVATAR,
    EVENT_ROOM_TOPIC,
    EVENT_ROOM_JOIN_RULES,
    EVENT_ROOM_CANON_ALIAS,
    EVENT_ROOM_ENCRYPT,

    EVENT_REDACTED,

    EVENT_ENCRYPTED,

    EVENT_MSG_MESSAGE,
    // EVENT_MSG_STICKER,

    EVENT_EPH_TYPING,
    EVENT_EPH_RECEIPT,
    EVENT_EPH_PRESENCE,
} matrix_event_type_t;

#endif //MATRIX_CLIENT_MATRIX_EVENT_TYPE_H
