#undef TEMPLATE_TYPE
#undef TEMPLATE_TYPE_IS_ARRAY
#undef TEMPLATE_TYPE_K
#undef TEMPLATE_TYPE_V
#undef TEMPLATE_TYPE_K_IS_ARRAY
#undef TEMPLATE_TYPE_V_IS_ARRAY
#undef TEMPLATE_PREFIX
#undef TEMPLATE_IS_KV